server:
  port: 8800
  servlet:
    application-display-name: baseServer

spring:
  profiles:
    active: test
  application:
    name: base-application

cfg:
  name: configFile
  file_url: application.yml