spring:
  redis:
    port: 6379
    host: localhost
#    url: http://localhost:6379
    password:
    timeout: 60000ms
    database: 0
    # 连接的客户端名称
    client-name: test
#    # 哨兵
#    sentinel:
#      # master 服务名称
#      master: redis_master
#      # 节点 host:port
#      nodes: localhost:6380,localhost:6381
#    # 集群
#    cluster:
#      # 节点
#      nodes: localhost:6380,localhost:6381,localhost:6382,localhost:6383,localhost:6384,localhost:6385
#      # 跨集群执行命令时要遵循的最大重定向数 maximum numbers of redirects to follow when executing command across the cluster
#      max-redirects: 3
    jedis:
      pool:
        max-ac: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
        # 空闲对象与线程之间运行的时间间隔 time between runs of the idle object evicted thread
#        time-between-eviction-runs:
#    lettuce:
#      # 默认 100ms
#      shutdown-timeout: 100ms
#      pool:
#        # 池中维护的最小的空闲连接数量 默认 0
#        min-idle: 0
#        # 池中最大的空闲连接数量 默认 8
#        max-idle: 8
#        # 池中活跃的连接最大数值 默认 8
#        max-active: 8
#        # 阻塞等待获取连接的最大时间，超时抛出异常，默认 -1ms
#        max-wait: -1ms
#        # 空闲对象与线程之间运行的时间间隔 time between runs of the idle object evicted thread
#        time-between-eviction-runs: