server:
  port: 8001
  servlet:
    application-display-name: rabbitServer

spring:
  profiles:
    active: local
  application:
    name: rabbit-application
  rabbitmq:
    host: 192.168.12.223
    port: 5672
    username: supplychain_local
    password: 123456
    virtual-host: /opec-oscs-local
    #    支持发布到交换机确认
    publisher-confirms: true
    #    支持发布队列返回
    publisher-returns: true
    listener:
      simple:
        #采用手动应答
        acknowledge-mode: manual
        # 当前监听容器数
        concurrency: 1
        # 最大数
        max-concurrency: 1
        # 是否支持重试 - 需配置在消费端，重试是在消费端-条件：抛出异常
        retry:
          enabled: true
          maxAttempts: 5
          initialInterval: 5000ms