server:
  port: 8010
  servlet:
    application-display-name: mybatisServer

spring:
#  profiles:
#    active: local
#  application:
#    name: mybatis-application
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/demo?useSSL=false&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

